# Generated by Django 4.1.3 on 2022-12-05 20:32
import os
from django.db import migrations

def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')


    Group.objects.create(name=os.environ.get('DJ_GROUP_CUSTOMERS'))
    Group.objects.create(name=os.environ.get('DJ_GROUP_OPERATORS'))


def delete_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')

    Group.objects.get(name=os.environ.get('DJ_GROUP_CUSTOMERS').delete)
    Group.objects.get(name=os.environ.get('DJ_GROUP_OPERATORS').delete)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_account_is_operator'),
    ]

    operations = [
        migrations.RunPython(create_groups, delete_groups)
    ]
