# Generated by Django 4.1.3 on 2022-12-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm_systems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
