# Generated by Django 4.1.3 on 2022-12-11 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alarm_systems', '0002_alter_camera_registrator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motionsensor',
            name='central',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alarm_systems.central'),
        ),
    ]
