# Generated by Django 4.1.3 on 2022-12-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm_systems', '0002_alter_customer_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='last_check',
            field=models.DateField(auto_now=True),
        ),
    ]
