# Generated by Django 4.1.3 on 2022-12-11 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alarm_systems', '0003_alter_motionsensor_central'),
    ]

    operations = [
        migrations.AlterField(
            model_name='central',
            name='system_types',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alarm_systems.system'),
        ),
    ]
