# Generated by Django 4.1.3 on 2022-12-08 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alarm_systems', '0003_alter_system_last_check'),
    ]

    operations = [
        migrations.RenameField(
            model_name='central',
            old_name='brand',
            new_name='manufacturer',
        ),
    ]
