# Generated by Django 4.1.3 on 2022-12-11 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alarm_systems', '0004_alter_central_system_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='registrator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alarm_systems.registrator'),
        ),
        migrations.AlterField(
            model_name='central',
            name='system_types',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alarm_systems.system'),
        ),
        migrations.AlterField(
            model_name='motionsensor',
            name='central',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alarm_systems.central'),
        ),
    ]
